name: easy_cache_manager
description: "High-performance Flutter caching with Hive NoSQL"
version: 0.0.1
homepage: https://github.com/kidpech/easy_cache_manager
repository: https://github.com/kidpech/easy_cache_manager
issue_tracker: https://github.com/kidpech/easy_cache_manager/issues
documentation: https://pub.dev/packages/easy_cache_manager

funding:
  - https://github.com/sponsors/kidpech

topics:
  - cache
  - caching
  - storage
  - offline
  - network

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core networking and HTTP client
  http: ">=0.13.0 <2.0.0"

  # Cross-platform file system and path utilities
  path_provider: ">=2.0.0 <3.0.0"
  path: ">=1.8.0 <2.0.0"

  # Cryptography for hashing and encryption
  crypto: ">=3.0.0 <4.0.0"

  # Database support - High-performance NoSQL storage
  hive: ">=2.2.3 <4.0.0"
  hive_flutter: ">=1.1.0 <2.0.0"

  # Reactive programming streams
  rxdart: ">=0.27.0 <1.0.0"

  # JSON serialization
  json_annotation: ">=4.7.0 <5.0.0"

  # Logging utilities
  logging: ">=1.1.0 <2.0.0"

  # Image caching widget is provided via our own widget; remove direct dependency to keep core light

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and analysis
  flutter_lints: ">=2.0.0 <4.0.0"
  very_good_analysis: ">=4.0.0 <6.0.0"

  # Testing utilities
  mockito: ">=5.0.0 <6.0.0"
  test: ">=1.21.0 <2.0.0"
  integration_test:
    sdk: flutter

  # Code generation for Hive models
  build_runner: ">=2.3.0 <3.0.0"
  json_serializable: ">=6.5.0 <7.0.0"
  hive_generator: ">=2.0.0 <3.0.0"

  # Performance testing
  flutter_driver:
    sdk: flutter

  # Competitor cache for fair comparisons (dev-only)
  stash: ">=4.0.0 <6.0.0"
  stash_memory: ">=4.0.0 <6.0.0"

# Configuration for the package analyzer
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This package supports all Flutter platforms but is implemented as a pure Dart package
  # No native platform code required thanks to Hive's cross-platform support

  # Package assets (none currently)
  # assets:
  #   - assets/icons/
  #   - assets/images/

  # Package documentation assets (none currently)
  # docs:
  #   - doc/api/
  #   - doc/guides/
