name: easy_cache_manager
description: "High-performance Flutter caching with Hive NoSQL storage, Clean Architecture, intelligent eviction policies, and cross-platform WASM support."
version: 0.1.3
homepage: https://github.com/Kidpech-code/easy_cache_manager
repository: https://github.com/Kidpech-code/easy_cache_manager
documentation: https://pub.dev/packages/easy_cache_manager

funding:
  - https://github.com/sponsors/Kidpech-code

topics:
  - cache
  - caching
  - storage
  - offline
  - network

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # Core networking and HTTP client
  http: ^1.5.0

  # Cross-platform file system and path utilities
  path_provider: ^2.1.5
  path: ^1.9.1

  # Universal IO for WASM compatibility
  universal_io: ^2.2.2

  # Web support for WASM compatibility
  web: ^1.1.1

  # Cryptography for hashing and encryption
  crypto: ^3.0.6

  # Database support - High-performance NoSQL storage
  hive: ">=2.2.3 <4.0.0"
  hive_flutter: ">=1.1.0 <2.0.0"

  # Reactive programming streams
  rxdart: ">=0.28.0 <1.0.0"

  # JSON serialization
  json_annotation: ^4.9.0

  # Logging utilities
  logging: ^1.3.0

  # Image caching widget is provided via our own widget; remove direct dependency to keep core light

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and analysis
  flutter_lints: ^3.0.2
  very_good_analysis: ^5.1.0

  # Testing utilities
  mockito: ^5.4.5
  test: ^1.25.15
  integration_test:
    sdk: flutter

  # Code generation for Hive models
  build_runner: ^2.5.4
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1

  # Performance testing
  flutter_driver:
    sdk: flutter

  # Competitor cache for fair comparisons (dev-only)
  stash: ^5.2.0
  stash_memory: ^5.2.0

# Configuration for the package analyzer
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This package supports all Flutter platforms but is implemented as a pure Dart package
  # No native platform code required thanks to Hive's cross-platform support

  # Package assets (none currently)
  # assets:
  #   - assets/icons/
  #   - assets/images/

  # Package documentation assets (none currently)
  # docs:
  #   - doc/api/
  #   - doc/guides/
